// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).
// This class and method can not be confused and modified !!
package com.hacknife.example.briefness;

import android.view.View;

import com.hacknife.iplayer.DataSource;
import com.hacknife.iplayer.IPlayer;
import com.hacknife.iplayer.state.ContainerMode;

/**
 * author  : Hacknife
 * e-mail  : 4884280@qq.com
 * github  : http://github.com/hacknife
 * project : Briefness
 */
public class ViewInjector {
    public static boolean injector(View view, Object value) {
        if (view instanceof IPlayer && value instanceof DataSource) {
            ((IPlayer) view).setDataSource((DataSource) value);
        }
        return false;
    }
}
